const errorTypes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DUPLICATE_RESOURCE_ERROR: "DUPLICATE_RESOURCE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INCORRECT_CREDENTIALS: "INCORRECT_CREDENTIALS",
};

export default errorTypes;
